### ISSUE TITLE
Wizard class missing arcane traditions (schools)

### ISSUE THREAD

**Issue by ShooShoSha** [vitusventure/5thSRD#102]
There is only a single school listed for wizards. Several are missing:

- Abjuration
- Conjuration
- Divination
- Enchantment
- Illusion
- Necromancy
- Transmutation

**Comment by vitusventure** [comment]
First, thanks for taking the time to make this pull request!

Unfortunately, we can only include content on the site that Wizards has published in the official SRD. Only the SRD content is published under the open gaming license, all other content is subject to copyright.

Currently the SRD only includes a single school for wizards. 🙁
