### ISSUE TITLE
Formatting error in Wolf entry

### ISSUE THREAD

**Issue by mortenbra** [vitusventure/5thSRD#115]
The entry for the wolf (http://5thsrd.org/gamemaster_rules/monsters/wolf/) doesn't properly separate between the "Keen Hearing and Smell" and the "Pack Tactics" abilities, and the headline for the latter should be bolded.

**Comment by vitusventure** [comment]
Fixed in https://github.com/vitusventure/5thSRD/commit/8b8b69802e03ba96bca0ff94b2b36dd3b7fa0652
