### ISSUE TITLE
Formatting error in Xorn entry

### ISSUE THREAD

**Issue by mortenbra** [vitusventure/5thSRD#116]
The entry for Xorn ( http://5thsrd.org/gamemaster_rules/monsters/xorn/ ) has a formatting error in the Actions block: The Claw attack is not properly bolded and separated from the Multiattack entry.

**Comment by vitusventure** [comment]
Thanks for the note!

Fixed in: https://github.com/vitusventure/5thSRD/commit/fa6123380ca68871216bd3830b4bffdf7a359cdf
