### ISSUE TITLE
Formatting error in Satyr entry

### ISSUE THREAD

**Issue by mortenbra** [vitusventure/5thSRD#117]
The entry for Satyr ( http://5thsrd.org/gamemaster_rules/monsters/satyr/ ) has a formatting error in the Actions block: The Shortbow attack is not properly bolded and separated from the Shortsword entry.

**Comment by vitusventure** [comment]
Thanks for the note!

Fixed in https://github.com/vitusventure/5thSRD/commit/e0df0c4b6768885b2c315ab37e719baec9d242f2
