### ISSUE TITLE
Formatting error in Giant Bat entry

### ISSUE THREAD

**Issue by mortenbra** [vitusventure/5thSRD#119]
The entry for the giant bat (http://5thsrd.org/gamemaster_rules/monsters/giant_bat/) doesn't properly separate between the "Echolocation" and the "Keen Hearing" abilities, and the headline for the latter should be bolded.

**Comment by vitusventure** [comment]
Fixed in https://github.com/vitusventure/5thSRD/commit/3d36cae7bba972ea4d7817e49ef400f32fc8ac4c

Thanks!
