### ISSUE TITLE
Formatting error in Giant Toad entry

### ISSUE THREAD

**Issue by mortenbra** [vitusventure/5thSRD#120]
The entry for the giant bat (http://5thsrd.org/gamemaster_rules/monsters/giant_toad/) doesn't properly separate between the "Amphibious" and the "Standing Leap" abilities, and the headline for the latter should be bolded.

**Comment by vitusventure** [comment]
Fixed in https://github.com/vitusventure/5thSRD/commit/18eac0bef6c93e52a8cb61699005d5ce14abf27f

Thanks!
