### ISSUE TITLE
Formatting error in Ioun Stone entry

### ISSUE THREAD

**Issue by mortenbra** [vitusventure/5thSRD#121]
The entry for the ioun stones (http://5thsrd.org/gamemaster_rules/magic_items/ioun_stone/) doesn't properly separate between the "Awareness (Rare)" and the "Fortitude (Very Rare)" variants, and the headline for the latter should be bolded.

**Comment by vitusventure** [comment]
Fixed in https://github.com/vitusventure/5thSRD/commit/6313cbd50c6d033527d5890f30762f00d4856c73
