### ISSUE TITLE
Formatting error in Elf (Drow) entry

### ISSUE THREAD

**Issue by mortenbra** [vitusventure/5thSRD#122]
The entry for the drow (http://5thsrd.org/gamemaster_rules/monsters/elf_drow/) doesn't properly separate between the alignment and the Armor Class, which should start on a separate line.

**Comment by vitusventure** [comment]
Fixed in https://github.com/vitusventure/5thSRD/commit/a81e581b6907c2ec8a1aad873aeef4c5f75983b7
