### ISSUE TITLE
Formatting error in Lamia entry 

### ISSUE THREAD

**Issue by mortenbra** [vitusventure/5thSRD#123]
The entry for the lamia (http://5thsrd.org/gamemaster_rules/monsters/lamia/) doesn't properly separate between the "Claws" and the "Dagger" actions, and the headline for the latter should be bolded.

**Comment by vitusventure** [comment]
Fixed in https://github.com/vitusventure/5thSRD/commit/ed38cbc1a15c2fae3e2cbc91e4fe6ce20200d952
