### ISSUE TITLE
Phase Spider wrongly listed as Beast on "Monsters by Type" page

### ISSUE THREAD

**Issue by mortenbra** [vitusventure/5thSRD#125]
On the Monsters by Type page ( http://5thsrd.org/gamemaster_rules/monster_indexes/monsters_by_type/ ), the Phase Spider is wrongly listed under "Beast". It should be listed under "Monstrosity".

**Comment by vitusventure** [comment]
Fixed in https://github.com/vitusventure/5thSRD/commit/9a6ebc348237cf2d1654afb1da416b9d1b8d7c5f
