### ISSUE TITLE
Formatting error in Potion of Water Breathing entry

### ISSUE THREAD

**Issue by mortenbra** [vitusventure/5thSRD#126]
The entry for Potion of Water Breathing ( http://5thsrd.org/gamemaster_rules/magic_items/potion_of_water_breathing/ ) lacks proper formatting of header, type, description, etc.

**Comment by vitusventure** [comment]
Fixed in https://github.com/vitusventure/5thSRD/commit/4d7ac1e359908170d742c4981d4ba700fa167797
