### ISSUE TITLE
Improved font selection in new theme

### ISSUE THREAD

**Issue by mortenbra** [vitusventure/5thSRD#129]
The theme for the site was changed a while back, and now uses a sans-serif font for all content. IMHO, this gives the site a very "boring" (and also "modern") look. A serif font would be more appropriate for a fantasy/medieval RPG such as D&D/5E.

Please consider adding something like this to the site stylesheet:

```
.pure-g [class*=pure-u] {
    font-family: "Baskerville Old Face",Baskerville,"Hoefler Text",Garamond,"Times New Roman",serif;
}
```

Comparison of current and suggested font selection:

![Capture3](https://user-images.githubusercontent.com/9341579/98437337-98e7f180-20e1-11eb-86ce-5bc82a67bdb4.JPG)

**Comment by vitusventure** [comment]
I agree! Switched to a slightly different stack, but serif nonetheless.

Changed in https://github.com/vitusventure/5thSRD/commit/4618169ba94216790e98b6e471beed5432e60b3c
