### ISSUE TITLE
Gnoll monster entry formatting

### ISSUE THREAD

**Issue by ron-reaser** [vitusventure/5thSRD#14]
The monster entry for Gnoll contains some mangled formatting on the italics for its Spear attack action.

http://www.5thsrd.org/gamemaster_rules/monsters/gnoll/#actions

**Comment by vitusventure** [comment]
Thanks for the note!

Corrected here: https://github.com/vitusventure/5thSRD/commit/46840c30240a9447360595c5d0bf53b5c49e2a2a

Expect to see the site updated in the next few days.
