### ISSUE TITLE
Cleric spell list shows cantrips twice

### ISSUE THREAD

**Issue by ron-reaser** [vitusventure/5thSRD#15]
On the spell list page for Clerics the Cantrips are listed both at the top and the bottom.

http://www.5thsrd.org/spellcasting/spell_lists/cleric_spells/

The top section lists them as "Cantrips (0 Level)" and includes 7 spells. The bottom section lists them as "Cantrips" and is missing Spare the Dying. All other class spell lists use the "Cantrips (0 Level)" heading and place them at the top.

**Comment by vitusventure** [comment]
Looks like this error was due to an old cantrips.txt file in the spell lists.

Corrected here: https://github.com/vitusventure/5thSRD/commit/faa20507bf737897b26fcdfb49fda226d2542af4

I will be doing a deployment in the next few days which will pick up this change.
