### ISSUE TITLE
Cure Wounds spell entry

### ISSUE THREAD

**Issue by ron-reaser** [vitusventure/5thSRD#25]
The spell page for Cure Wounds contains part of Dancing Lights as well.

http://www.5thsrd.org/spellcasting/spells/cure_wounds/

The Dancing Lights spell page is fine.

**Comment by vitusventure** [comment]
This was actually fixed here: fb7362638fadceb3fdfe7fc396edc83f3859d922 but was pending deployment.

Deployment is now underway, expect to see updated pages within the next few hours as caches are invalidated.
