### ISSUE TITLE
Shield +1, +2, or +3 link doesn't work

### ISSUE THREAD

**Issue by rooneg** [vitusventure/5thSRD#30]
The link to Shield, +1, +2, or +3 on the magic items index doesn't work, presumably because the underlying file for it doesn't have the "or" in the filename. Either that file needs renaming or the link needs fixing.

**Comment by vitusventure** [comment]
Resolved with merge of your pull request: 447422b313ba65924fafe3ea4a572102ad20f35b.

Thanks!
