### ISSUE TITLE
Change to theme attribution

### ISSUE THREAD

**Issue by ron-reaser** [vitusventure/5thSRD#32]
My GitHub account name has changed. It was formerly Bloodcinder. Now it is ron-reaser, which is my actual name. If you want to keep the attribution to me, please change the URL to https://github.com/ron-reaser and just cite me as Reaser (just my last name, that's what I go by). However, if you want to remove the attribution, I have no problem with that at all. The commit history is attribution enough, really.

**Comment by vitusventure** [comment]
Updated to new link and name in commit above.  I am going to keep the attribution in, because the theme is totally awesome.  Deployment will happen within the next few days.
