### ISSUE TITLE
Update generate_indexes.py to support Python 3.6

### ISSUE THREAD

**Issue by theloremaster** [vitusventure/5thSRD#40]
In Python 3.6, the format of the print command changed, to require that the text to be printed be bounded by parentheses. If a user tries to build the site under Python 3.6, every print command will fail.

Can we have an alternate generate_indexes.py file created for Python 3.6 users?

**Comment by SG004** [comment]
I have added and alternate generate_indexes.py file called generate_indexes3.6.py that bounds all the print statements with parentheses. May I do a pull request?

**Comment by vitusventure** [comment]
I rewrote the index generation code in 8fcaaf510b467cebbea8bad8df1c333a2ea08116 to be more version agnostic, and have been deploying with 3.6.  This should solve your issue, sorry for the long wait!
