### ISSUE TITLE
Issue with speak with animals "cantrip"

### ISSUE THREAD

**Issue by adikavemen** [vitusventure/5thSRD#41]
The speak with animals spell is in the cantrips section if you sort the SRD by levels. The spell is supposed to be a 1st level spell.

**Comment by vitusventure** [comment]
Thanks for the note!  I have corrected the file here: https://github.com/vitusventure/5thSRD/commit/d4592e99ab1901da7d657bfead1c016d1e048bd7.

The site should be updated in the next few days!
