### ISSUE TITLE
Finish Class Lists

### ISSUE THREAD

**Issue by spearitless** [vitusventure/5thSRD#44]
It seems like a lot of the classes are only partially listed, such as Barbarian only having Berserker, Monk only having Way of Open Hand, etc.

**Comment by vitusventure** [comment]
The website can only contain content which Wizards of the Coast has released under the Open Gaming License. For 5th edition, the OGL content is a subset of what is released commercially. Wizards only releases part of the rules for free, whereas the complete rules are published as official books.
