### ISSUE TITLE
QUESTION: can I update with Monster Manual?

### ISSUE THREAD

**Issue by stevethecollier** [vitusventure/5thSRD#46]
I have a copy of the monster manual, would it be legal for me to create a pr with all the entries?

I'm willing to do the work, just not sure if it would be a waste of time.

Thx

**Comment by vitusventure** [comment]
Thanks for asking ahead of time!

Unfortunately, the site can only include items in the System Reference Document, as those are released under the Open Gaming License.  The content from the books is subject to copyright, and thus cannot be published on the site.

Happy adventuring!
