### ISSUE TITLE
Damage and Healing Page Layout - Micro Errors

### ISSUE THREAD

**Issue by Farreep** [vitusventure/5thSRD#5]
http://5thsrd.org/combat/damage_and_healing/
- [x] Damage types: **Poison** subheading needs to be put on new line (currently concatenated to **Piercing** line)
- [x] Monsters and Death: **Knocking a creature out** looks like a heading in the middle of that paragraph.  Should that be there?  Or on a new line?

**Comment by vitusventure** [comment]
Thanks for filing this issue!

The problems you noted were corrected in: https://github.com/vitusventure/5thSRD/commit/ba88b043bcdc16e9c5bd806ebd307635c19abe22

I expect to redeploy the site tonight, so you should see these changes go live then.

**Comment by Farreep** [comment]
Great!  You're ahead of me :)  

Thanks for your hard work on this!  I really like the whole process.
