### ISSUE TITLE
QUESTION: can I use this content in iOS app ?

### ISSUE THREAD

**Issue by jurex** [vitusventure/5thSRD#90]
Hi guys, I would like to ask if I can use this content to generate SRD content in my iOS app. The app is called Encounter+ and it is used by DM's to run combat encounters. I've received a lot of requests recently to include searchable rules and this seems like a very good data source. I can give credits to all contributors if necessary (besides SRD license to Wizards ofc). Thanks!

**Comment by vitusventure** [comment]
Please feel free to use the content in any way you like (as long as you conform to the OGL)!

Glad to hear it would be useful for you!

**Comment by jurex** [comment]
Thank you, @vitusventure 😊 Will definitely let you know, when I'll have this ready.

**Comment by LouisMilotte** [comment]
Related Necro,

How do we cite you for using your materials?

**Comment by vitusventure** [comment]
Mostly, make sure you conform to all the terms in the Open Gaming License (see license.md for the link).

Other than that, I would appreciate a link to the site if you use the content, but there is nothing binding about that!
